#ifndef TOOLS_BUILD_DEFS_HASKELL_TESTS_HSC2HS_INCLUDES_C_DEP_H_
#define TOOLS_BUILD_DEFS_HASKELL_TESTS_HSC2HS_INCLUDES_C_DEP_H_

typedef struct {
  int x;
  int y;
} foo;

#endif  // TOOLS_BUILD_DEFS_HASKELL_TESTS_HSC2HS_INCLUDES_C_DEP_H_
