# This package provides a binary that outputs a cabal macros file
# for libraries build with the cabal_haskell_package macro.
load("//bzl:def.bzl", "haskell_binary")

haskell_binary(
    name = "GenerateCabalMacros",
    srcs = ["GenerateCabalMacros.hs"],
    visibility = ["//visibility:public"],
)
